server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: stats_server_route
          uri: lb://stats-server
          predicates:
            - Path=/hit, /stats

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /requests/**, /requests

        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/users/*/events/*/comments/**, /comments/**, /admin/comments/**

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/**
